### ISSUE TITLE
Allow multiple Movie DB links for a series.

### ISSUE THREAD

**Issue by CatmanIX** [japanesemediamanager/ShokoDesktop#182] opened 2015-07-28 06:11 UTC
Probably a rare use-case, but for "series" like Mardock Scramble, which is three movies grouped together on AniDB, but isn't listed on TVDB because it isn't a TV show, it would be nice to associate each movie on MDB with the related "episode" on AniDB so we can get the proper metadata.

**Comment by CatmanIX** [comment] 2015-07-28 06:12
I guess you could say this is related to issue #66.

**Comment by ElementalCrisis** [comment] 2016-01-21 03:42
Duplicate of #66.

**Comment by jmediamanager** [comment] 2016-02-10 23:54
Ignore the Fix above, I put the wrong issue number

**Closed** 2017-07-16 09:22 UTC
Labels: Duplicate, Enhancement - New Feature
