### ISSUE TITLE
Client displays incorrect episode title

### ISSUE THREAD

**Issue by Remnence** [japanesemediamanager/ShokoDesktop#510] opened 2017-01-22 14:34 UTC
![incorrect display](https://cloud.githubusercontent.com/assets/1884580/22183186/9d926a2e-e07d-11e6-8163-99a700e70279.PNG)

**Comment by Remnence** [comment] 2017-01-22 14:36
Files that auto-renamed on import display their previous title despite having been renamed properly.

MSSQL 2014

**Comment by da3dsoul** [comment] 2017-01-22 14:53
Okay

**Comment by Remnence** [comment] 2017-01-22 18:13
@da3dsoul lol, I admit its not gamebreaking but it may be a symptom of a larger issue. Especially considering all the renaming related issues I've been having lately. It's definitely a new symptom since 3.7.0.3.

**Comment by da3dsoul** [comment] 2017-01-22 18:15
Yeah, I can guess what causes it. I was in a bad mood so my response was minimal

**Comment by ElementalCrisis** [comment] 2017-06-28 01:39
@da3dsoul was this fixed?

**Comment by da3dsoul** [comment] 2017-06-28 01:49
Maybe? I don't know what caused it. I didn't really touch the series list

**Comment by da3dsoul** [comment] 2017-06-28 01:49
Maybe? I don't know what caused it. I didn't really touch the series list

**Comment by ElementalCrisis** [comment] 2017-06-28 01:55
Deleted the duplicate reply.

I can't reproduce so for now I'll close it, @Remnence if you encounter this again when 3.7.5.0 is released, please reopen this issue.

**Closed by ElementalCrisis** 2017-06-28 01:55 UTC
Labels: Bug - Low Priority
